import { UserProfile, UserAccount, AlbumFolder, StickyNote, PinOrPost, AppNotification } from '../types';

export const INITIAL_PROFILE: UserProfile = {
  id: 'profile-maymay',
  name: 'maymay ❤️‍🩹',
  handle: '@maymay',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  cover: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1400&q=80',
  bio: 'colecionando momentos pequenos que viram memórias infinitas ✨ Apaixonada por fotografia analógica, café e arte.',
  customTitle: 'Nossa História de Amor 💖✨',
  customSubtitle: 'Nosso cantinho de memórias e afeto.',
  bgColor: '#ffeef4',
  fontFamily: 'font-caveat',
  layoutMode: 'mosaic',
  themeColor: '#f43f5e',
  relationshipDate: '2024-06-12',
  pinnedQuote: 'A vida mora nos detalhes sutis.',
};

export const INITIAL_ACCOUNTS: UserAccount[] = [
  {
    id: 'user-1',
    email: 'maymay@exemplo.com',
    handle: '@maymay',
    name: 'maymay ❤️‍🩹',
    password: '123',
    profile: INITIAL_PROFILE,
  },
];

export const INITIAL_ALBUMS: AlbumFolder[] = [
  {
    id: 'album-1',
    name: 'Nossa História de Amor 💖',
    cover: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=600&q=80',
    pinCount: 18,
    profileId: 'profile-maymay',
    color: '#f43f5e',
    description: 'Nossos primeiros encontros, passeios e sorrisos.',
  },
  {
    id: 'album-2',
    name: 'Retratos & Momentos 📸',
    cover: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=600&q=80',
    pinCount: 24,
    profileId: 'profile-maymay',
    color: '#ec4899',
    description: 'Fotos favoritas da minha pessoa favorita no universo todo.',
  },
  {
    id: 'album-3',
    name: 'Trilhas Sonoras & Vídeos 🎶',
    cover: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    pinCount: 9,
    profileId: 'profile-maymay',
    color: '#8b5cf6',
    description: 'Músicas e clipes que marcaram momentos especiais.',
  },
  {
    id: 'album-4',
    name: 'Decoração & Apê Acolhedor 🌿',
    cover: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=600&q=80',
    pinCount: 12,
    profileId: 'profile-maymay',
    color: '#10b981',
    description: 'Inspirações de plantas, iluminação e móveis vintage.',
  },
];

export const INITIAL_STICKY_NOTES: StickyNote[] = [
  {
    id: 'note-1',
    targetProfileId: 'profile-maymay',
    authorName: 'Lucas 💛',
    content: 'Te amo infinitamente! Obrigado por cada segundo juntos 💖',
    color: 'pink',
    sticker: '💖',
    rotation: -1.5,
    createdAt: 'Hoje às 14:20',
    pinned: true,
    reactions: { '❤️': 12, '🥺': 5, '✨': 8 },
  },
  {
    id: 'note-2',
    targetProfileId: 'profile-maymay',
    authorName: 'Amigos do Bairro',
    content: 'Não esquece do piquenique no parque neste sábado! Leve a câmera analógica 📸',
    color: 'yellow',
    sticker: '🛹',
    rotation: 1.2,
    createdAt: 'Ontem às 19:15',
    pinned: false,
    reactions: { '🔥': 4, '🤘': 3 },
  },
  {
    id: 'note-3',
    targetProfileId: 'profile-maymay',
    authorName: 'Mãe & Família',
    content: 'Fiz aquele bolo de cenoura com chocolate que você adora! Passa aqui mais tarde pegar um pedaço 🍰☕',
    color: 'peach',
    sticker: '☕',
    rotation: -1,
    createdAt: 'Hoje às 10:45',
    pinned: false,
    reactions: { '❤️': 7, '🤤': 6 },
  },
];

export const INITIAL_POSTS: PinOrPost[] = [
  {
    id: 'post-1',
    authorId: 'profile-maymay',
    authorName: 'maymay ❤️‍🩹',
    authorHandle: '@maymay',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    title: 'Nossa tarde de chuva e café ☕🌧️',
    content: 'Dias nublados ficam mil vezes mais quentinhos quando a gente divide um fone de ouvido. Não troco essa paz por nada nesse mundo!',
    imageUrl: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    aspectRatio: 'tall',
    boardId: 'album-1',
    boardName: 'Nossa História de Amor 💖',
    mediaEmbed: {
      type: 'youtube',
      url: 'https://www.youtube.com/watch?v=jfKfPfyJRdk',
      embedId: 'jfKfPfyJRdk',
      title: 'Melodias Suaves para Relaxar & Ler',
      artistOrChannel: 'Canal Acústico & Chill',
      thumbnail: 'https://img.youtube.com/vi/jfKfPfyJRdk/hqdefault.jpg',
    },
    tags: ['café', 'amor', 'nostalgia', 'trilhasuave'],
    likes: 42,
    reposts: 7,
    commentsCount: 6,
    createdAt: 'Há 25 minutos',
    likedByMe: true,
    isPinned: true,
    comments: [
      {
        id: 'c1',
        authorName: 'Lucas 💛',
        authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        text: 'Melhor tarde do mundo! Essa música é linda demais ✨',
        createdAt: 'Há 10 minutos',
      },
    ],
  },
  {
    id: 'post-2',
    authorId: 'profile-maymay',
    authorName: 'maymay ❤️‍🩹',
    authorHandle: '@maymay',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    title: 'Primavera florescendo por aqui 🌸🌷',
    content: 'As flores no caminho floresceram todas de uma vez hoje! Deixando esse registro aqui para lembrar que tudo tem seu tempo certo de florir.',
    imageUrl: 'https://images.unsplash.com/photo-1522748906645-95d8adfd52c7?auto=format&fit=crop&w=800&q=80',
    aspectRatio: 'tall',
    boardId: 'album-2',
    boardName: 'Retratos & Momentos 📸',
    tags: ['primavera', 'flores', 'estética', 'delicadeza'],
    likes: 63,
    reposts: 9,
    commentsCount: 4,
    createdAt: 'Há 3 horas',
    likedByMe: true,
  },
  {
    id: 'post-3',
    authorId: 'profile-maymay',
    authorName: 'maymay ❤️‍🩹',
    authorHandle: '@maymay',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    title: 'Luz dourada do entardecer 🌇',
    content: 'O sol se pondo no horizonte através da janela. Uma foto simples com câmera analógica para guardar o momento com carinho.',
    imageUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?auto=format&fit=crop&w=800&q=80',
    aspectRatio: 'square',
    boardId: 'album-1',
    boardName: 'Nossa História de Amor 💖',
    tags: ['entardecer', 'fotografia', 'pordosol'],
    likes: 51,
    reposts: 8,
    commentsCount: 3,
    createdAt: 'Ontem',
    likedByMe: false,
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    type: 'reminder',
    actorName: 'Lucas 💛',
    actorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    message: 'colou um recadinho doce no seu mural: "Te amo infinitamente! 💖"',
    target: 'Mural de Lembretes',
    timestamp: 'Há 5 min',
    read: false,
  },
  {
    id: 'notif-2',
    type: 'like',
    actorName: 'Mãe & Família',
    actorAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80',
    message: 'curtiu sua publicação no álbum "Nossa História de Amor 💖"',
    target: 'Publicação #post-1',
    timestamp: 'Há 20 min',
    read: false,
  },
  {
    id: 'notif-3',
    type: 'music',
    actorName: 'Lucas 💛',
    actorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    message: 'adicionou um novo item na aba Hobby',
    target: 'Hobby',
    timestamp: 'Há 1 hora',
    read: true,
  },
];
